use_frameworks!

platform :ios, '10.0'

target 'AFServiceNet_Example' do
  pod 'AFServiceNet', :path => '../'

  target 'AFServiceNet_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
